# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b0210c8e19816c5cce6dbd053f852d2dacb23b0e913451f2492aed2b8f69ac145307aacdffe1fe6baefa4e9863a65ee129eefa7a2f58e5fe946001cc2b8e0d

test:
  secret_key_base: 5c5638fad9479fdaf2d9e35bffae5bdb654c1231b7dafd7fba110a20d7bac3f455392aa4761d98cfeb90fd695104c72aaefa118588701ffbe1eebfaaa4fbacf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
